name: Tox Workflow Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.8]

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Pytest and any other packages
        run: pip install pytest flake8 awscli
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambdas/requirements.txt
      - name: Run Tests
        run: make test