name: Flake8 Workflow Check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Run PEP8 Tests
      run: |
        cd ./aws/eks/
        python -m pip install --upgrade pip virtualenv
        make pep8
  